[project]
name = "GrandBlue"
version = "0.1.0"
description = "Grand Blue mobile app"
requires-python = ">=3.10"


dependencies = [
    "flet>=0.83.1",
    "flet-geolocator>=0.1.0",
    "flet-map>=0.24.0",
    "httpx",
    "requests"
]

[tool.flet]
company = "GrandBlue"
permissions = ["location"]

[tool.flet.android.permission]
"android.permission.INTERNET" = true
"android.permission.ACCESS_FINE_LOCATION" = true
"android.permission.ACCESS_COARSE_LOCATION" = true

[dependency-groups]
dev = [
    "flet-cli>=0.83.1",
    "flet-desktop>=0.83.1",
    "flet-web>=0.83.1"
]

[tool.flet.app]
path = "."